### ISSUE TITLE
Can't Build Android Project- Request for a demo starter project with some examples

### ISSUE THREAD

**Issue by ahmedbilal205** [thoebert/krosbridge#2]
Thanks for the code, looks really interesting. I wanted to achieve this for sometime. Look interesting. I am having the same issue as the other issue reported, where my build is failing after including the code. If you could provide some example project and more documentation, that would be really helpful.

**Comment by thoebert** [comment]
See my resolution there https://github.com/thoebert/krosbridge/issues/1#issuecomment-1873537058
